import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/components/navbar";
import { ThemeProvider } from "@/components/ThemeProvider"; 
import AuthProvider from "@/components/AuthProvider";
import { CartProvider } from "@/app/context/CartContext";
import "./globals.css";
import CartDrawer from "@/components/CartDrawer";
import { Toaster } from 'react-hot-toast';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AgroMarket",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning 
    >
      <body className="min-h-full flex flex-col bg-gray-50 text-gray-900 dark:bg-gray-950 dark:text-gray-100 transition-colors duration-300">
        <ThemeProvider>
          <AuthProvider>
            <CartProvider>
              <Navbar/>
              <CartDrawer/>
              
              {children}
              
              {/* --- UPGRADED: Premium Top-Right Toaster --- */}
              <Toaster 
                position="top-right"
                reverseOrder={false}
                gutter={8}
                toastOptions={{
                  // Default sleek styling for all toasts
                  style: {
                    background: '#1f2937', // Custom dark gray (Tailwind gray-800)
                    color: '#f9fafb', // Light text
                    borderRadius: '12px',
                    padding: '16px 20px',
                    fontSize: '14px',
                    fontWeight: '600',
                    boxShadow: '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
                  },
                  // Custom theme for Success toasts
                  success: {
                    iconTheme: {
                      primary: '#10b981', // Matches your Emerald-500
                      secondary: '#fff',
                    },
                  },
                  // Custom theme for Error toasts
                  error: {
                    iconTheme: {
                      primary: '#ef4444', // Matches Tailwind Red-500
                      secondary: '#fff',
                    },
                  },
                }} 
              />
              
            </CartProvider>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}